config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pets, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:new, :create]
    collection do
      get :map
    end
  end
  resources :bookings, only: [:index, :edit, :update]
  get '/dashboard', to: 'users#show', as: 'dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pet
  validates :start_date, presence: true
  validate :end_time_after_start_time # custom validation

  def calculate_total_price
    self.total_price = ((end_date - start_date).to_i + 1) * pet.price_per_day
  end

  private

  def end_time_after_start_time
    errors.add(:end_date, "can't be in the past") unless end_date >= start_date
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :bookings
  validates :name, presence: true
  validates :species, presence: true
  validates :price_per_day, presence: true
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :pets
  has_many :bookings
  # has_many :pets, through: :bookings, as: :pets_to_borrow
  # validates :username, presence: true, uniqueness: true
  # validates :age, numericality: { greater_than: 17 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: [:index, :map], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index, :map], unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:age, :username])

    devise_parameter_sanitizer.permit(:account_update, keys: [:age, :username])
  end


  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @booking = Booking.new
    @pet = Pet.find(params[:pet_id])
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.user = current_user
    @pet = Pet.find(params[:pet_id])
    @booking.pet = @pet
    @booking.calculate_total_price
    if @booking.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :find_pet, only: [:update, :edit, :destroy, :show]
  skip_before_action :authenticate_user!, only: [:show, :index, :map]

  def index
    @pets = policy_scope(Pet).order(created_at: :desc)
    if params[:query].present?
      @pets = Pet.where("species ILIKE ?", "%#{params[:query]}%")
    else
      @pets = Pet.all
    end
  end

  def map
    @pets = policy_scope(Pet).order(created_at: :desc)
    @pets = @pets.where if params[:species]
    @pets = # second filter
    @pets = # third filter
    @markers = @pets.geocoded.map do |pet|
      {
        lat: pet.latitude,
        lng: pet.longitude,
        marker_info_window: render_to_string(partial: "marker_info_window", locals: { pet: pet }),
        image_url: pet.photos.first.url
      }
    end
  end

  def show
    authorize @pet
  end

  def new
    @pet = Pet.new
    authorize @pet
  end

  def create
    @pet = Pet.new(pet_params)
    authorize @pet
    @pet.user = current_user
    if @pet.save
      redirect_to pets_path
    else
      render :new
    end
  end

  def update
    authorize @pet
    @pet.update(pet_params)
  end

  def edit
    authorize @pet
  end

  def destroy
    authorize @pet
  end

  private

  def pet_params
    params.require(:pet).permit(:species, :name, :toilet_trained, :description, :price_per_day, :address, photos: [])
  end

  def find_pet
    @pet = Pet.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @pets = current_user.pets
    authorize @pets
    @bookings = current_user.bookings
    @pet = Pet.new
    authorize @pet
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_pet_photo_carousel.html.erb
  <div class="card-pet">
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <% @pet.photos.each_with_index do |photo, index| %>
          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to= "<%= index.to_s %>" aria-label="<%= "Slide #{index + 1}"%>"
          class=<%= index==0 ? "active" : "" %>
          aria-current=<%= index==0 ? "true" : "" %>
          ></button>
        <% end %>
      </div>

      <div class="carousel-inner">
        <% @pet.photos.each_with_index do |photo, index| %>
          <div class=
          "<%= index==0 ? "carousel-item active" : "carousel-item" %>"
          >
            <%= cl_image_tag photo.key, height: 300, width: 600, crop: :fill, gravity: :face, class: "d-block w-100" %>
          </div>
        <% end %>
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="container row justify-content-center ">
    <div class="col-7 my-5">

      <div class="pt-4">
      <h1 class ="text-center">Book your new buddy <%= @pet.name %> <i class="fas fa-dog"></i></h1>

      <%= render 'pet_photo_carousel' %>

      <div class="mt-4">
        <%= simple_form_for [@pet, @booking] do |f| %>
          <%= f.input :start_date, :as => :date, :start_year => 2022,
          :end_year => Date.today.year + 2,
          :order => [ :day, :month, :year], :required => true %>
          <%= f.input :end_date, :as => :date, :start_year => 2022,
          :end_year => Date.today.year + 2,
          :order => [ :day, :month, :year], :required => true %>
          <%# <h6> Total Price: $ </h6> %>
          <%# @booking.total_price&.round %>

          <div class="d-grid gap-2">
            <%= f.submit "Book your new buddy!", class: "btn btn-action btn-lg btn-block" %>
            <h2 class="card-pet-button btn btn-action"><i class="fas fa-long-arrow-alt-left" style="color:white"></i>
              <%= link_to " Back", pets_path %>
            </h2>
          </div>
        <% end %>

      </div>

    </div>
  </div>
</div>
<%# <i class="fas fa-dog">  </i>%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Petbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
      <%= render 'shared/navbar' %>
      <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="background-container d-flex py-4 align-items-center">
  <div class="landing-banner d-flex justify-content-left align-items-center px-5">
    <p>
      <span data-controller="typed-js" style="color: rgb(180, 180, 180); text-shadow: 3px 3px 7px rgb(0, 0, 0, 0.2)"></span>
    </p>
  </div>

  <div class="img-container d-flex flex-column justify-content-end align-items-end">
    <div class="description-container">
      <%= image_tag '3d-desgin.png', class: "3d-img", size: "210" %>
      <div>
        <%= link_to "I'm an Owner", dashboard_path,  class: "button-role" %>
      </div>
    </div>
    <div class="description-container">
      <%= image_tag '3d-desgin2.png', class: "3d-img", size: "210" %>
      <div>
        <%= link_to "I'm a Borrower", pets_path,  class: "button-role" %>
      </div>

    </div>
  </div>
</div>

app/views/pets/_marker_info_window.html.erb
<h2><%= link_to "#{pet.name} - #{pet.species}", pet_path(pet)  %> </h2>
<p><%= link_to pet.address.titleize, pet_path(pet) %></p>
<p><%= link_to "$ #{pet.price_per_day} / Day", pet_path(pet) %></p>

app/views/pets/_new.html.erb
<div class="container row justify-content-center mt-2">
  <div class="col-6 mb-5">
    <%= simple_form_for @pet  do |f| %>
      <%= f.input :name %>
      <%= f.input :species %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :toilet_trained %>
      <%= f.input :price_per_day %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <div class="d-grid gap-2">
        <%= f.submit "Add your pet", class: "btn btn-action btn-lg btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pets/index.html.erb
<div class="container">
  <h3 class="m-3">Top-rated pets to borrow in your area:
    <%= link_to map_pets_path do %>
      <%= icon('fas', 'map-marked') %>
    <% end %>
  </h3>
  <div class="container white-cards">
      <% @pets.each do |pet| %>
          <%= link_to pet_path(pet), class: "card white-card p-2" do %>
            <div class="white-card-img">
              <% if pet.photos.attached? %>
                <%= cl_image_tag pet.photos.first.key, crop: :fill %>
              <% else %>
                <%= image_tag "pet_default_shadow.jpg", crop: :fill %>
              <% end %>
            </div>
            <div class="pet-info">
              <p> <strong> <i class="fas fa-tag"></i> </strong> <%= pet.name %> </p>
              <p> <strong> <i class="fas fa-paw"></i></strong> <%= pet.species %> </p>
              <p> <strong> <i class="fas fa-dollar-sign"></i> </strong> <%= (pet.price_per_day).round %>  per day </p>
            </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/pets/map.html.erb
<div class="container">
  <h3>Top-rated pets to borrow in your area:
    <%= link_to pets_path do %>
        <% icon('fas', 'list-alt') %>
      <% end %>
  </h3>

  <div class="container">
    <div style="width: 100%; height: 600px;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/pets/new.html.erb
<div class="container row justify-content-center ">
  <div class="col-6 mb-5">
    <h1>Add a pet for rent</h1>
    <%= simple_form_for @pet  do |f| %>
      <%= f.input :name %>
      <%= f.input :species %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :toilet_trained %>
      <%= f.input :price_per_day %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <div class="d-grid gap-2">
        <%= f.submit "Add your pet", class: "btn btn-action btn-lg btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pets/show.html.erb
<div class="container row justify-content-center" id="adjustment">
  <div class="col-6">
    <div class="pt-4 d-flex justify-content-between align-items-center">
      <div>
        <h1> <%= @pet.name %> </h1>
          <% if !@pet.address.nil? %>
        <p> <%= @pet.address.capitalize %> </p>
          <% end %>
      </div>
        <div>
          <h2 class="card-pet-button btn btn-action"><i class="fas fa-long-arrow-alt-left" style="color: white"></i>
            <%= link_to " Back", pets_path %>
          </h2>
        </div>
    </div>

  <%= render 'pet_photo_carousel' %>

      <div class="card-pet-bottom p-3 p-3">
        <div class="card-pet-price mb-4 d-flex align-items-center">
          <div>
            <h2>$<%= (@pet.price_per_day).round %> / day</h2>
          </div>
          <div>
            <h2><strong> <i class="fas fa-paw"></i></strong> <%= @pet.species %></h2>
          </div>
          <div>
            <span><i class="fas fa-toilet"></i> <strong><%= @pet.toilet_trained ? 'I can hold it in' : 'I may leave a mess' %></strong> </span>
          </div>
          <div>
            <h2 class="card-pet-button btn btn-sec-action">
            <%= link_to "Book Me!", new_pet_booking_path(@pet) %>
            </h2>
          </div>
            </div>
          </div>
            <div class="d-flex justify-content-space-around align-items-center pb-3 px-3">
              <div class="w-50">
                <p  style="font-size:16px">Description: <%= @pet.description %></p>
              </div>
              <div class="w-50">
                <h6 class="owner text-right">Owned by <%= @pet.user.email.partition('@').first.capitalize %></h6>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_bookings.html.erb
<div class="white-cards">
  <% @bookings.each do |booking| %>
      <%= link_to pet_path(booking.pet), class: "card white-card p-2 mt-2" do %>
        <div class="white-card-img">
          <% if booking.pet.photos.attached? %>
            <%= cl_image_tag booking.pet.photos.first.key, crop: :fill %>
          <% else %>
            <%= image_tag "pet_default_shadow.jpg", crop: :fill %>
          <% end %>
        </div>
        <div class="white-card-description p-2 position-relative">
          <h6> <i class="fas fa-tag"></i> <%= booking.pet.name %> </h6>
          <h6> <i class="fas fa-paw"></i> <%= booking.pet.species %> </h6>
          <h6> <i class="fas fa-map-marked"></i> <%= booking.pet.address %> </h6>
          <h6> <i class="far fa-calendar-alt"></i> <%= booking.start_date.strftime('%d %b %y') %> - <%=  booking.end_date.strftime('%d %b %y') %> </h6>
          <h6> Total Price: $<%= booking.total_price&.round %> </h6>
          <p class="text-danger position-absolute cancel-button"> Cancel </p>
          <p class="text-secondary position-absolute amend-button"> Amend </p>
        </div>
      <% end %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    Ⓒ 2022 Petbnb Inc. Privacy Terms & Condition
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light navbar-lewagon content-wrapper">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag 'Logo.png'%>
    <% end %>
    <%= form_tag pets_path, method: :get, class: "input-group search-bar w-25" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search pets to borrow by species"
        %>
      <%= button_tag type: "submit", class: "btn btn-action" do %>
        <%= icon('fas', 'search') %>
      <% end %>
    <% end %>
    <div class="d-inline-flex  p-1 align-items-center">
      <%# list drop down %>
      <div class="d-flex justify-content-sm-between profile me-1">
        <ul class="navbar-nav me-3">
          <%= image_tag "dropdown.png", class: "dropdown-toggle dropdown-list-icon", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
              <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <%= link_to "Home", root_path, class: "dropdown-item" %>
              <%= link_to "Lease a pet", new_pet_path, class: "dropdown-item" %>
              <%= link_to "View listed pets", pets_path, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: "btn btn-primary bordered" %>
            <% end %>
          </div>
        </ul>
      </div>
   </div>
 </div>
</div>

app/views/shared/_your_pets.html.erb
<div class="white-cards">
  <% @pets.each do |pet| %>
    <%= link_to pet_path(pet), class: "card white-card p-2 mt-2" do %>
        <div class="white-card-img">
          <% if pet.photos.attached? %>
            <%= cl_image_tag pet.photos.first.key, crop: :fill %>
          <% else %>
            <%= image_tag "pet_default_shadow.jpg", crop: :fill %>
          <% end %>
        </div>
        <div class="white-card-description p-2 position-relative">
          <h6> <i class="fas fa-tag"></i> <%= pet.name %> </h6>
          <% if pet.bookings.size == 0 %>
              <h6> <%= pet.name %> has no bookings </h6>
          <% end %>
          <% pet.bookings.each do |booking| %>
            <h6> <%= booking.user.email %> </h6>
            <h6> <i class="far fa-calendar-alt"></i> <%= booking.start_date.strftime('%d %b %y') %> - <%=  booking.end_date.strftime('%d %b %y') %> </h6>
          <% end %>
          <p class="text-danger position-absolute cancel-button"> Edit </p>
        </div>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">

<div class="d-flex mt-2 mr-2">
  <h2 class="card-pet-button btn btn-sm btn-action mt-2"><i class="fas fa-long-arrow-alt-left" style="color: white"></i>
    <%= link_to " Back", pets_path %>
  </h2>
  <h2 class="mt-2 ml-5 margin-fix-last"> <%= current_user.email.partition('@').first.capitalize %>'s Dashboard</h2>
</div>


<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="bookings-tab" data-bs-toggle="tab" data-bs-target="#bookings" type="button" role="tab" aria-controls="bookings" aria-selected="true">Your Bookings</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="pets-tab" data-bs-toggle="tab" data-bs-target="#pets" type="button" role="tab" aria-controls="pets" aria-selected="false">Your Pets</button>
  </li>
   <li class="nav-item" role="presentation">
    <button class="nav-link" id="new-tab" data-bs-toggle="tab" data-bs-target="#new" type="button" role="tab" aria-controls="new" aria-selected="false">Add a new pet</button>
  </li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="bookings" role="tabpanel" aria-labelledby="bookings-tab">
    <%= render 'shared/bookings' %>
  </div>

  <div class="tab-pane" id="pets" role="tabpanel" aria-labelledby="pets-tab">
    <%= render 'shared/your_pets' %>
  </div>

  <div class="tab-pane" id="new" role="tabpanel" aria-labelledby="new-tab">
    <%= render 'pets/new' %>
  </div>
</div>







</div>